--Python RFM analizi için gerekli verilerin çekilmesi
SELECT 
USERS.ID,
USERS.NAMESURNAME AS ISIM_SOYISIM,
USERS.CREATEDDATE AS ILK_KAYIT,
INVOICES.DATE_ AS SON_SATINALMA_TARIHI,
INVOICEDETAILS.AMOUNT AS SATINALMA_MIKTARI,
INVOICEDETAILS.LINETOTAL AS TOPLAM_DEGER

FROM ORDERS
INNER JOIN USERS ON USERS.ID = ORDERS.USERID
INNER JOIN INVOICES ON INVOICES.ORDERID = ORDERS.ID
INNER JOIN INVOICEDETAILS ON INVOICEDETAILS.INVOICEID = INVOICES.ID
ORDER BY USERS.ID, INVOICES.DATE_

UPDATE INVOICES
SET DATE_ = DATEADD(DAY, 
        ABS(CHECKSUM(NEWID())) % DATEDIFF(DAY, (SELECT MIN(CREATEDDATE) FROM USERS), '2020-03-27'), 
        (SELECT CREATEDDATE FROM USERS WHERE USERS.ID = (SELECT USERID FROM ORDERS WHERE ORDERS.ID = INVOICES.ORDERID))
    )