# -*- coding: utf-8 -*-
"""market-rfm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkDIErBzGA59yYZEbgG7IqWehD5rZilU
"""

import pandas as pd
import datetime as dt

#Veri ayırma yöntemi: ';'
#Sütun isimlendirmeleri manuel yapılmalı.
df_ = pd.read_csv('/content/rfm-verileri.csv', sep=';', header=None)

df_.head()

df = df_.copy()

df.columns = ['ID','Isim-Soyisim','Kayit-Tarihi','Satin-Alim-Tarihi','Miktar','Tutar'] #sütun isimlendirme

df.head()

df.isnull().sum() #eksik verimiz bulunmamakta.

df.describe() #Betimsel istatistik, Tutar Değeri Çok Yüksek

df.shape

df.info()

df['Kayit-Tarihi'] = pd.to_datetime(df['Kayit-Tarihi'])
df['Satin-Alim-Tarihi']=pd.to_datetime(df['Satin-Alim-Tarihi'])

df.info()

df['Satin-Alim-Tarihi'].max()

today_date=dt.datetime(2022,1,20)

rfm= df.groupby('ID').agg({
    'Satin-Alim-Tarihi':(lambda x:(today_date-x.max()).days), #recency
    'Miktar':(lambda y:y.nunique()), #frequency
    'Tutar':(lambda t:t.sum()) #monetary
}
)

rfm.columns=['Recency','Frequency','Monetary']

rfm.head()

rfm['Recency_Score']=pd.qcut(rfm['Recency'],5,labels=[5,4,3,2,1])
rfm['Frequency_Score']=pd.qcut(rfm['Frequency'].rank(method='first'),5,labels=[1,2,3,4,5])
rfm['Monetary_Score']=pd.qcut(rfm['Monetary'],5,labels=[1,2,3,4,5])

rfm.head()

rfm['rfm_score'] = (
    rfm['Recency_Score'].astype(str) +
    rfm['Frequency_Score'].astype(str) +
    rfm['Monetary_Score'].astype(str))

rfm.head()

seg_map = {
    r'[1-2][1-2][1-5]': 'uykuda',
    r'[1-2][3-4][1-5]': 'riskli',
    r'[1-2]5[1-5]': 'kaybedilmemeli',
    r'3[1-2][1-5]': 'uyumak_uzere',
    r'33[1-5]': 'dikkat',
    r'[3-4][4-5][1-5]': 'sadik',
    r'41[1-5]': 'umit_verici',
    r'51[1-5]': 'yeni',
    r'[4-5][2-3][1-5]': 'potansiyel_sadik',
    r'5[4-5][1-5]': 'sampiyon'
}

rfm['segment'] = rfm['rfm_score'].replace(seg_map, regex=True)

rfm.head()

rfm.describe().T

rfm[['segment','Recency','Frequency','Monetary']].groupby('segment').agg(['mean','count'])

